export const FilterConstants = {
  ROLES_CONSTANTS: 'ROLES_CONSTANTS',
  NUMBEROFEMPLOYEES_CONSTANTS: 'NUMBEROFEMPLOYEES_CONSTANTS',
  EXPERIENCE_CONSTANTS: 'EXPERIENCE_CONSTANTS',
  JOBSETTING_CONSTANTS: 'JOBSETTING_CONSTANTS',
  TECHSTACK_CONSTANTS: 'TECHSTACK_CONSTANTS',
  MINIMUMBASEPAYSALARY_CONSTANTS: 'MINIMUMBASEPAYSALARY_CONSTANTS',
  SEARCHEDDATA_CONSTANTS: 'SEARCHEDDATA_CONSTANTS',
};
